import { IoPlayOutline, IoPauseOutline } from "react-icons/io5";
import { RxShare1, RxDotsVertical } from "react-icons/rx";
import { TfiShare } from "react-icons/tfi";

export const TABLE_ARRAY = [
  {
    id: 1,
    play: <IoPlayOutline />,
    pause: < IoPauseOutline />,
    image: "BG.jpg",
    title: "Kataware Doki",
    artist: "Mitsuha",
    label: "Your Name",
    streams: "424k",
    totalLength: 192,
    mp3: require("../Songs/katawaredoki.mp3"),
    share: <RxShare1 />,
    share2: <TfiShare />,
    more: <RxDotsVertical />,
  },
  {
    id: 2,
    play: <IoPlayOutline />,
    pause: <IoPauseOutline />,
    image: "Kids.jpg",
    title: "The Rumbling",
    artist: "Yeager",
    label: "AOT",
    streams: "669k",
    totalLength: 159,
    mp3: require("../Songs/therumbling.mp3"),
    share: <RxShare1 />,
    share2: <TfiShare />,
    more: <RxDotsVertical />,
  },
  {
    id: 3,
    play: <IoPlayOutline />,
    pause: <IoPauseOutline />,
    image: "Guitar.jpg",
    title: "Golden Wind",
    artist: "JoJo",
    label: "Gold Requiem",
    streams: "643k",
    totalLength: 170,
    mp3: require("../Songs/goldenwind.mp3"),
    share: <RxShare1 />,
    share2: <TfiShare />,
    more: <RxDotsVertical />,
  },
  {
    id: 4,
    play: <IoPlayOutline />,
    pause: <IoPauseOutline />,
    image: "Rockhard.jpg",
    title: "Good Morning World",
    artist: "Senku",
    label: "Masterpiece",
    streams: "969k",
    totalLength: 106,
    mp3: require("../Songs/goodmorningworld.mp3"),
    share: <RxShare1 />,
    share2: <TfiShare />,
    more: <RxDotsVertical />,
  },
];

